# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'
  name: Azure Pipelines
  demands: maven

#Your build pipeline references an undefined variable named ‘Parameters.mavenPOMFile’. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab. See https://go.microsoft.com/fwlink/?linkid=865972
#Your build pipeline references an undefined variable named ‘ mvn help:evaluate -Dexpression=project.version -q -DforceStdout ’. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab. See https://go.microsoft.com/fwlink/?linkid=865972
#Your build pipeline references an undefined variable named ‘APP_VERSION’. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab. See https://go.microsoft.com/fwlink/?linkid=865972

steps:
- task: Maven@3
  displayName: 'Maven pom.xml'
  inputs:
    mavenPomFile: 'pom.xml'

- script: |
   echo "======Show Directory====="
   pwd
   
   echo "======List Files====="
   ls
   
   echo "======Read Files====="
   cat ./pom.xml
   
   echo "======App Version====="
   appversion=$( mvn help:evaluate -Dexpression=project.version -q -DforceStdout )
   echo "##vso[task.setvariable variable=APP_VERSION;]$appversion"
  displayName: 'Get App Version'

- script: |
   echo $(APP_VERSION) >> version.txt
  displayName: 'Create Version File'

- task: CopyFiles@2
  displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
  inputs:
    SourceFolder: '$(system.defaultworkingdirectory)'
    Contents: |
      '**/*.jar'
      'version.txt'
    TargetFolder: '$(build.artifactstagingdirectory)'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: Hello-World'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'
    ArtifactName: 'Hello-World'

- task: Docker@2
  displayName: buildAndPush
  inputs:
    containerRegistry: 'hexinlai-docker-repo'
    repository: 'hexinlai/hello-world'
    tags: '$(APP_VERSION)'
